spring:
  activemq:
    packages:
      trusted:
      - dev.demo.demomq.model
      - java.time
    broker-url: tcp://localhost:61616
    source: demo.source
    destination: demo.destination

  jms:
    pub-sub-domain: false

